name: CI

on: [push]

env:
  TEST: docker.pkg.github.com/$GITHUB_REPOSITORY/${{ github.event.repository.name }}

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: env
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/${{ github.event.repository.name }}:develop
    - name: Run tests
      run: docker run --env-file .env.test docker.pkg.github.com/$GITHUB_REPOSITORY/${{ github.event.repository.name }}:develop python -m pytest
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: $GITHUB_REPOSITORY/${{ github.event.repository.name }}:develop
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
