name: Build and publish Docker image

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-18.04
    steps:
    - run: env
    - uses: actions/checkout@v1
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
    - name: Tag (latest) the Docker image
      run: docker tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} docker.pkg.github.com/${IMAGE_NAME}:latest
      if: github.ref == 'refs/heads/master'
    # - name: Run mypy against the image
    #   run: docker run docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} mypy
    - name: Run tests against the image
      run: docker run --env-file tests/.test.env docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} python -m pytest
    - name: Login to regitry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Publish image
      run: docker push docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
