name: Build and publish Docker image

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-18.04
    steps:
    - run: env
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$IMAGE_NAME:${GITHUB_REF##*/}
    - name: Run tests against the image
      run: docker run --env-file tests/.env.test docker.pkg.github.com/$IMAGE_NAME:${GITHUB_REF##*/} python -m pytest
    - name: Publish image to GitHub packages
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: $IMAGE_NAME:${GITHUB_REF##*/}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
